# Generated by Django 5.1.2 on 2025-01-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_homeowner_property_delete_announcement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homeowner',
            old_name='first_name',
            new_name='homeowner',
        ),
        migrations.RemoveField(
            model_name='homeowner',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='homeowner',
            name='username',
        ),
        migrations.RemoveField(
            model_name='property',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='property',
            name='property_name',
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('House', 'House'), ('Condo', 'Condo'), ('Lot', 'Lot')], max_length=20),
        ),
    ]
