# Generated by Django 5.1.2 on 2025-01-31 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_first_name_homeowner_homeowner_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Homeowner',
        ),
    ]
