# Generated by Django 5.1.2 on 2025-01-31 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_feedback_homeowner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='created_at',
        ),
    ]
