# Generated by Django 5.1.2 on 2025-01-31 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_feedback_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='homeowner',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('House', 'House'), ('Condo', 'Condo'), ('Lot', 'Lot')], max_length=10),
        ),
    ]
